### ISSUE TITLE
Create our own action for devs to use in a new, simpler, workflow

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#420]
(Others welcome to work on this too)

How do we write an action that other devs run in their workflow so they hardly have to manage anything to do with actions?

Edit:
I used two repos to test this action out as I developed, since I haven't yet experimented with developing an action on a branch other than the default branch:
The action repo: https://github.com/plocket/ALKiln_action
The subscriber/workflow repo: https://github.com/plocket/docassemble-CompositeActionsTest

# Questions

More detailed answers to these questions are in the comments below as I iterate on the process, but I'll sum up my findings up here.

## Running a composite action:
- [x] Can we publish an action in our existing ALKiln repo despite all the files there now? (**Answer:** it seems so. I put action.yml into the root of a fork and it seemed that was all that was necessary)
   - [x] Will those files hijack the process, running our tests instead of theirs? (**Answer:** It seems not. It thinks it's in the user's repo.)
- [x] Can we log the output to the user's console as this is happening, not just in our little pocket of the console? (**Answer:** I'm pretty sure the answer to this is 'no'.)
- [x] Alternatively, can we log output directly to the user's console at the end? I realize we're logging it in our step, but our step has a bunch of other stuff in it right now. ~Maybe it really would be worth breaking these parts out into their own actions or steps despite the fact that we'll need to create the `env:` variables each time~ (see various notes in below comments about env vars). Even if we break them out into their own actions, they'll still log inside the composite action and be just as buried. (**Answer:** I think it may not be worth logging in two places and potentially confusing people. It may be enough to just log in our action. An error will take people right there and a good job name in their workflow should help direct them other times.)
- [x] Can we reference actions inside our action? (**Answer:** yes - more recently added. See https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/)
   - [x] If not, how do we handle that? Don't we need those? (**Answer:** not needed)
- [x] How do we run node in the action? (**Answer:** With `uses:`, which we can use now. We are using an explicit version of node)
- [x] How to pass in env vars? (**Answer:** see comments below. Except secrets, they seem to already be passed in, but have to be referenced in the step itself, either with `env:`, which seems to be limited to one `run:` or with `run: echo...`.)
- [x] How do we pass in secrets? (**Answer:** We can pass secrets in as inputs.)
- [x] Can we create files in the dev's repo with js? (**Answer:** Yes, we can add the file with the name of the Project.)
- [x] Can we create artifacts in the dev's test? (**Answer:** Yes! We can do it the way the dev's workflow does it now!)
- [x] How do we get inputs for manual runs? (**Answer:** We just get them naturally. We can refer to them the same way as before.)
- [ ] Is there a way for our action to decide what inputs can be given in a manual run?

## Process
- [x] Do we need to publish a new version of the action for the action edits to take effect? (**Answer:** yes)
- [x] How to use semver in the dev workflow? What's the equivalent of npm `^3.0.0`? (**Answer:** we update old tags called v3 and avoid updating specific tags like v3.0.3. See [issue below](https://github.com/SuffolkLITLab/ALKiln/issues/420#issuecomment-993959965)) ~(so far: Not "v3.0.0", not "v3")~
- How do we keep the action version aligned with the repo version? Do we just update it when we update the action and skip all the previous non-action versions? Automate the process (more work)? (See #406 now)
- How do we try editing our action without committing to our main branch constantly? Can versions be developed on other branches? They can definitely be "pre-released" with tags and such that don't change the main version tag. (See #406 now)
- Can you publish new code on the same tag? (Answer: ~No~ Supposedly, but I haven't managed to do it yet.) (See #406 now)
- [ ] What's the difference between a regular action, as before, and a composite action now? Can we just use a regular action with `jobs:`, etc?

Part of #128.

# Security
> Here's some github documentation about good practices for using third party actions: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions. I'm not sure which of those we can help our users use, but it might be a place to start.

Edit: Here's a section on permissions for GitHub workflows: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions. That's what our action will be running in. We don't even use GITHUB_TOKEN or any other personal access tokens, though I'm not sure how we can guarantee that. We can only write instructions for people to make sure none of their secrets are PATs.

See #425 for more comments/discussions on security concerns.

# Composite actions, initial notes
> [Maybe these are relevant to us, though I'm not sure how it's different from a regular action... It uses `using: composite`, which I've not used before, I believe. Still, maybe this is actually what I've been think of as an action and I just had thought it was older than it is.]
> 
> Originally: "Composite actions" are a thing. Not sure exactly how they fit in. Maybe they fit in more with a user's github org that can make a composite action that uses our action for all their packages. https://dev.to/n3wt0n/github-composite-actions-nest-actions-within-actions-3e5l (video here: https://www.youtube.com/watch?v=OqJyrZUUGTw)

**Comment by plocket** [comment]
This works in the root of the project:
```yml
name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"
runs:
  using: "composite"
  steps:
    - run: echo "testing composite action"
      shell: bash
```

Need to publish a tag. I used `v3.0.0`.

**Comment by plocket** [comment]
Logging env vars in our action logs the dev repo's env vars:
```ymlname: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"
runs:
  using: "composite"
  steps:
    - run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      shell: bash
    - run: echo "Repo address is $REPO_URL"
      shell: bash
# Gets "https://github.com/plocket/docassemble-TestPrivateRepo"
```

**Comment by plocket** [comment]
Using node in a composite action - this might be useful: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#creating-an-action-metadata-file

Example given:
```yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
```

I just realized we don't currently have a script I can practice in the private repo...

**Comment by plocket** [comment]
New public repo created to continue testing: https://github.com/plocket/docassemble-CompositeActionsTest

**Comment by plocket** [comment]
Trying to get secrets didn't work. What did work was `run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV`

**Comment by plocket** [comment]
This also worked, but you can't do the same key (`run`) multiple times in that format. There must be a way, though. Why couldn't I use `env:` less nested? Maybe the secrets were messing things up. I'll try again.

```yml
  steps:
    - name: Env vars
      env:
        BRANCH_PATH: ${{ github.ref }}
      shell: bash
      run: echo "$BRANCH_PATH"
      #run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      #run: echo "Repo address is $REPO_URL"
      #run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
```

**Comment by plocket** [comment]
This broke:
```yml
  env:
    BRANCH_PATH: ${{ github.ref }}
  #  BASE_URL: ${{ secrets.SERVER_URL }}
  #  PLAYGROUND_EMAIL: ${{ secrets.PLAYGROUND_EMAIL }}
  #  PLAYGROUND_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
  #  PLAYGROUND_ID: ${{ secrets.PLAYGROUND_ID }}
  #  EXTRA_LANGUAGES: ${{ secrets.EXTRA_LANGUAGES }}

  steps:
    - run: echo "$BRANCH_PATH"
      shell: bash
    - run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      shell: bash
    - run: echo "Repo address is $REPO_URL"
      shell: bash
    - run: echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash
```

Error messages were:
```
Error: plocket/ALKiln/v3.0.11/action.yml (Line: 8, Col: 18):
Error: plocket/ALKiln/v3.0.11/action.yml (Line: 15, Col: 3): Unexpected value 'steps'
Error: plocket/ALKiln/v3.0.11/action.yml (Line: 8, Col: 18): Unrecognized named-value: 'github'. Located at position 1 within expression: github.ref
Error: plocket/ALKiln/v3.0.11/action.yml (Line: 15, Col: 3): Unexpected value 'steps'
Error: System.ArgumentNullException: Value cannot be null. (Parameter 'You are using a composite action but there are no steps provided in plocket/ALKiln/v3.0.11/action.yml.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load plocket/ALKiln/v3.0.11/action.yml
```

**Comment by plocket** [comment]
Broken because no output was there for `$BRANCH_PATH`:
```yml
  steps:
    - name: env vars
      shell: bash
      run: echo "env var test"
      env:
        BRANCH_PATH: ${{ github.ref }}
    - run: echo "$BRANCH_PATH"
      shell: bash
```

**Comment by plocket** [comment]
Pushing workflow I found at :

```
git add action.yml
git commit -m "Add action"
git push
git tag -a -m "Description of this release" v1
git push --follow-tags
```

Do we need both pushes? Can this be done in one push? It really does look like it, which is a shame.

**Comment by plocket** [comment]
(Getting inputs)[https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs]

(Send out outputs)[https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions]

**Comment by plocket** [comment]
Passed in inputs.
Our action:
```yml
name: "Composite action attempt 1"
description: "Try to get this composite action to run in a private repo"

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "Server url is ${{ inputs.SERVER_URL }}"
      shell: bash
```

Their workflow:
```yml
name: Use composite action
on:
  push:
  workflow_dispatch:

jobs:
  composite-test:
    runs-on: ubuntu-latest
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - id: is_id_needed
        uses: plocket/ALKiln@v16
        with:
          SERVER_URL: "some server url"
      - run: echo "Finished using composite action"
```

**Comment by plocket** [comment]
Passing in the secret worked too, and it kept the secret hidden in the output as `***`. Just changed the `SERVER_URL` to
```yml
SERVER_URL: "${{ secrets.SERVER_URL }}"
```

**Comment by plocket** [comment]
This gets someone's package.json:
```yml
    - run: |
        FILE=./package.json
        if test -f "$FILE"
        then
          echo "$FILE exists."
        else
          echo "File does not exist"
        fi
      shell: bash
```

**Comment by plocket** [comment]
This worked to run `npm install`

Ours:

```yml
    - run: |
        npm install
      shell: bash
```

Theirs:
```yml
jobs:
  composite-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: is_id_needed
        uses: plocket/ALKiln@v28
        with:
          SERVER_URL: "${{ secrets.SERVER_URL }}"
          PLAYGROUND_EMAIL: "${{ secrets.PLAYGROUND_EMAIL }}"
          PLAYGROUND_PASSWORD: "${{ secrets.PLAYGROUND_PASSWORD }}"
          PLAYGROUND_ID: "${{ secrets.PLAYGROUND_ID }}"
          EXTRA_LANGUAGES: "${{ secrets.EXTRA_LANGUAGES }}"
      
      - run: echo "Finished using composite action"
```

**Comment by plocket** [comment]
Artifacts: If we can't use actions, we probably just need to make a folder or a list of the artifacts to download, provide them in the output, and have the dev use the artifact action in their own repo to download whatever we give them.

**Comment by plocket** [comment]
I seem to be able to use actions in th ecomposite action!

```yml
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run ALKiln tests
      env:
        REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
        BRANCH_PATH: ${{ github.ref }}
        BASE_URL: ${{ inputs.SERVER_URL }}
        PLAYGROUND_EMAIL: ${{ inputs.PLAYGROUND_EMAIL }}
        PLAYGROUND_PASSWORD: ${{ inputs.PLAYGROUND_PASSWORD }}
        PLAYGROUND_ID: ${{ inputs.PLAYGROUND_ID }}
        EXTRA_LANGUAGES: ${{ inputs.EXTRA_LANGUAGES }}

      run: |
        echo -e "Repo is $REPO_URL\nBranch is $BRANCH_PATH\nServer is $BASE_URL\nPassword is ${{ inputs.PLAYGROUND_PASSWORD}}"
        npm install
        npm run setup
        npm run takedown
      shell: bash
```

**Comment by plocket** [comment]
For running based on success or failure, this might or might not be helpful: https://stackoverflow.com/questions/7402587/run-command2-only-if-command1-succeeded-in-cmd-windows-shell

Use && to only run on the success of a previous command. Thing is, I'm not sure they should actually be in the same `run:` or if they should be in separate `run:`s. From what I recall, each `run:` needs its own `env:`, so that would make a lot of duplication. On the other hand, the output might be a bit harder to read that way. I'm not sure.

Our local command is `npm run setup && npm run cucumber; npm run takedown`, which seems like the right move - run the test only if the setup succeeds. Always run takedown.

**Comment by plocket** [comment]
Test console output when trying to get inputs from a manual run.

Before dev repo added inputs (on push):
```
> npm run langs_setup && npm run cucumber -- $@
...
cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "docassemble/CompositeActionsTest/data/sources/example_test.feature"
```

After dev repo added inputs (tag added manually to run with input "@example_scenario_tag"):
```
> npm run langs_setup && npm run cucumber -- $@ "--tags" "@example_scenario_tag"
cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "--tags" "@example_scenario_tag" "docassemble/CompositeActionsTest/data/sources/example_test.feature"
```
Ran for 1m 10 seconds (because of the wait step I added)

After dev repo added inputs (tag added manually to run with input "@none"):
```
> npm run langs_setup && npm run cucumber -- $@ "--tags" "@none"
> cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "--tags" "@none" "docassemble/CompositeActionsTest/data/sources/example_test.feature"
```
Ran for 42 seconds

I think the difference in time and the output does show that the correct tag was used. The command apparently always lists all the files, even if none match the tag that was given.

Their code:
```yml
on:
  push:
  workflow_dispatch:
    inputs:
      extra_languages:
        description: 'Optional. A list of comma separated language names visible on buttons or links that change the language of the interview. Overrides the EXTRA_LANGUAGES repo secret.'
        default: ''
      tags:
        description: 'Optional. Use a "tag expression" specify which tagged tests to run (https://cucumber.io/docs/cucumber/api/#tag-expressions)'
        default: ''
```

**Comment by plocket** [comment]
This command is never displayed in the user's console from what I can tell:
```
npm run setup && npm run test -- ${{ github.event.inputs.tags && format('"--tags" "{0}"', github.event.inputs.tags) }}; npm run takedown
```

I don't love it because it's hard to tell what part of the process the tests are in. We might want to add our own console logs that are more explicit. Also, how do we make ALKiln's logs clearly belong to ALKiln? They just blend in with all the other logs right now.

**Comment by plocket** [comment]
Putting artifacts in the dev Action summary works like a charm! We can do it after takedown! (As long as we don't delete the files before takedown, of course)

Ours:
```yml
#...
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: "12"
    - run: npm install
      shell: bash
    - name: "ALKiln: Run tests"
      env:
        REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
        BRANCH_PATH: ${{ github.ref }}
        BASE_URL: ${{ inputs.SERVER_URL }}
        PLAYGROUND_EMAIL: ${{ inputs.PLAYGROUND_EMAIL }}
        PLAYGROUND_PASSWORD: ${{ inputs.PLAYGROUND_PASSWORD }}
        PLAYGROUND_ID: ${{ inputs.PLAYGROUND_ID }}
        EXTRA_LANGUAGES: ${{ inputs.EXTRA_LANGUAGES }}

      run: |
        echo -e "Repo is $REPO_URL\nBranch is $BRANCH_PATH\nServer is $BASE_URL"
        npm run setup && npm run test -- ${{ github.event.inputs.tags && format('"--tags" "{0}"', github.event.inputs.tags) }}; npm run takedown
      shell: bash
    - name: "ALKiln: Upload report"
      uses: actions/upload-artifact@v2
      # They will upload even if a previous step has failed
      if: ${{ always() }}
      with:
        name: report
        path: ./**/*_report_*
```

**Comment by plocket** [comment]
## Output

Output multiline string article from a year ago: https://trstringer.com/github-actions-multiline-strings/

Output during a run: Seems impossible just by the way things are happening? I don't think you can output outside of your step while it's going on. That would look very weird. I'm thinking about how the contents of a step are all collapsed under one arrow in the action output.

Output after an action: ??

Getting the cucumber output as well: ??

**Comment by plocket** [comment]
## Inputs

Is it possible to request workflow_dispatch inputs from outside a workflow? See the question posted at https://github.community/t/is-it-possible-to-request-workflow-dispatch-inputs-from-outside-a-workflow/217227

**Comment by plocket** [comment]
## Versioning actions

Complex issue. First off, versions are not checked for changes. Even if you specify down to the patch version, and even using npm, it doesn't actually prevent a developer from changing the code of the version after the version is published. It's all crazy out there and everything should be on fire.

That said, it's a system of norms and trust there are different ways to handle versioning and subscribing to versions.

A subscriber or developer can specify versions for `uses` in these kinds of ways:

### Tags
```
uses: username/reponame@v2.4.1
uses: username/reponame@v2
uses: username/reponame@whatever
# without the `v`
uses: username/reponame@2.4.1
```

A subscriber can choose any tag they want. A developer can update a tag (somehow, though I haven't figured out how) with new code whenever they want, but generally agrees to update the code of a tag like `v2` regularly with changes that aren't breaking and to never change things as specific as `v2.4.1`.

### Branches
```
uses: username/reponame@branchname
```

### Commits
I think subscribers can use commit `sha`s too, but I don't recall how or what the syntax is.

A subscriber then gets that branch, no matter what the updates have been. We can have branches, as mentioned in #___ such as `releases/v1`, `releases/v2`, and so on that people can subscribe to. We'd make sure to stick to those versions.

### Discussion
Using branches seems like less work to be because then we don't have to set up a separate process (either automatic or manual) for updating tags. That said, I think I vaguely remember something about tags being useful for something... Maybe this: We're not going to keep a branch around for every minor version, but the tag will stick around and be more accessible than a commit `sha` or whatever.

I suggest we talk amongst ourselves about pros and cons of tags. Our users can use whichever they prefer of what we can provide, but we should choose a sensible default and allow them to choose something more specific if they want, just like we'll do for the version of our package.

**Comment by plocket** [comment]
So far, we haven't been able to add fields to an action's manual run UI, but we are able to distinguish between vars passed in with `with:` vs. vars passed in with `workflow_dispatch` `input`:

Ours:
```
    - run: |
        echo "${{ inputs.EXTRA_LANGUAGES }}"
        echo "${{ github.event.inputs.extra_languages }}"
      shell: bash
```

Theirs
```yml
#...
on:
  push:
  workflow_dispatch:
    inputs:
      extra_languages:
        description: 'Optional. A list of comma separated language names visible on buttons or links that change the language of the interview. Overrides the EXTRA_LANGUAGES repo secret.'
        default: ''
#...
        with:
          EXTRA_LANGUAGES: "$EXTRA_LANGUAGES"
#...
```

Result with no EXTRA_LANGUAGES secret
```
Run echo ""
  echo ""
  echo "lang 1, lang 2, lang n"
```

This means we can handle the annoying language `if` statement

**Comment by plocket** [comment]
## Creating an environment variable dynamically in a composite action

I have no clue so far. This is what I'm trying and `$EXTRA_LANGUAGES` is coming out as an empty string:

Code:
```yml
    - name: "ALKiln: Run tests"
      env:
        REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
        BRANCH_PATH: "${{ github.ref }}"
        BASE_URL: "${{ inputs.SERVER_URL }}"
        PLAYGROUND_EMAIL: "${{ inputs.PLAYGROUND_EMAIL }}"
        PLAYGROUND_PASSWORD: "${{ inputs.PLAYGROUND_PASSWORD }}"
        PLAYGROUND_ID: "${{ inputs.PLAYGROUND_ID }}"
      run: |
        if ${{ github.event.inputs.extra_languages != '' }}
        then
          echo "Manually set languages: ${{ github.event.inputs.extra_languages }}"
          echo "EXTRA_LANGUAGES=${{ github.event.inputs.extra_languages }}" >> $GITHUB_ENV
        else
          echo "Use EXTRA_LANGUAGES secret: ${{ inputs.EXTRA_LANGUAGES }}"
          echo "EXTRA_LANGUAGES=${{ inputs.EXTRA_LANGUAGES }}" >> $GITHUB_ENV
        fi
        echo -e "\nRepo is $REPO_URL\nBranch is $BRANCH_PATH\nLanguages to test are $EXTRA_LANGUAGES\nOther information is secret\n"
      shell: bash
```

Output
```
Run if true
  if true
  then
    echo "Manually set languages: lang1, lang2"
    echo "EXTRA_LANGUAGES=lang1, lang2" >> $GITHUB_ENV
  else
    echo "Use EXTRA_LANGUAGES secret: ***"
    echo "EXTRA_LANGUAGES=***" >> $GITHUB_ENV
  fi
  echo -e "\nRepo is $REPO_URL\nBranch is $BRANCH_PATH\nLanguages to test are $EXTRA_LANGUAGES\nOther information is secret\n"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    REPO_URL: https://github.com/plocket/docassemble-CompositeActionsTest
    BRANCH_PATH: refs/heads/main
    BASE_URL: ***
    PLAYGROUND_EMAIL: ***
    PLAYGROUND_PASSWORD: ***
    PLAYGROUND_ID: ***
Manually set languages: lang1, lang2

Repo is https://github.com/plocket/docassemble-CompositeActionsTest
Branch is refs/heads/main
Languages to test are 
Other information is secret
```

To note especially:
```
...
Manually set languages: lang1, lang2
...
Languages to test are 
```

**Comment by plocket** [comment]
## Committed version

You can see it at the link, but I'll put it here for posterity:

Ours:
```yml
name: "ALKiln: Automated docassemble tests"
description: "Automatically test any docassemble interview in a any branch on your GitHub repository whenever you commit or push. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing."

inputs:
  SERVER_URL:
    description: 'The url of your docassemble server. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_EMAIL:
    description: 'The email of your docassemble testing account. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_PASSWORD:
    description: 'The password of your docassemble testing account. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  PLAYGROUND_ID:
    description: 'The id of your docassemble testing account. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: true
  EXTRA_LANGUAGES:
    description: 'Other languages you want to test. This should be in your GitHub SECRETS or the SECRETS of your org.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # Install node
    - name: "ALKiln: Install node package manager"
      uses: actions/setup-node@v1
      with:
        node-version: "12"
    - run: npm install
      shell: bash

    # Set environment variables
    - name: "ALKiln: Set environment variables"
      # If extra languages were set manually, override the repository
      # EXTRA_LANGUAGES secret with the manually set values
      run: |
        if ${{ github.event.inputs.extra_languages != '' }}
        then
          echo "Manually set languages: ${{ github.event.inputs.extra_languages }}"
          echo "EXTRA_LANGUAGES=${{ github.event.inputs.extra_languages }}" >> $GITHUB_ENV
        else
          echo "Use EXTRA_LANGUAGES secret: ${{ inputs.EXTRA_LANGUAGES }}"
          echo "EXTRA_LANGUAGES=${{ inputs.EXTRA_LANGUAGES }}" >> $GITHUB_ENV
        fi
        echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_ENV
        echo "BRANCH_PATH=${{ github.ref }}" >> $GITHUB_ENV
        echo "BASE_URL=${{ inputs.SERVER_URL }}" >> $GITHUB_ENV
        echo "PLAYGROUND_EMAIL=${{ inputs.PLAYGROUND_EMAIL }}" >> $GITHUB_ENV
        echo "PLAYGROUND_PASSWORD=${{ inputs.PLAYGROUND_PASSWORD }}" >> $GITHUB_ENV
        echo "PLAYGROUND_ID=${{ inputs.PLAYGROUND_ID }}" >> $GITHUB_ENV
      shell: bash
    - name: "ALKiln: confirm info"
      run: echo -e "\nRepo is $REPO_URL\nBranch ref is $BRANCH_PATH\nManually added languages are $EXTRA_LANGUAGES\nAll other data is secret\n"
      shell: bash

    # Run tests
    - name: "ALKiln: Create a Project and pull the package from GitHub"
      run: npm run setup
      shell: bash
    - name: "ALKiln: Run tests"
      if: ${{ success() }}
      run: npm run test -- ${{ github.event.inputs.tags && format('"--tags" "{0}"', github.event.inputs.tags) }}
      shell: bash
    - run: echo -e "\n\n====ALKiln could not create a project on your server's testing account or pull your package into it. Check the messages above this line.\n\n"
      if: ${{ failure() }}
      shell: bash
    - name: "ALKiln: Delete project from docassemble test account"
      if: ${{ always() }}
      run: npm run takedown
      shell: bash

    # Upload artifacts that subscribers can download on the Actions summary page
    - name: "ALKiln: Upload errors to action summary artifacts"
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: errors
        path: ./**/error*.jpg
    - name: "ALKiln: Upload screenshots to action summary artifacts"
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./**/screenshot*.jpg
    - name: "ALKiln: Upload downloaded files to action summary artifacts"
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: downloads
        path: ./**/downloads_*
    - name: "ALKiln: Upload report to action summary artifacts"
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: ./**/*_report_*
```

Theirs:
```yml
name: Use the ALKiln testing framework
description: "Use the ALKiln testing framework to test interviews. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing."

on:
  push:
  workflow_dispatch:
    inputs:
      extra_languages:
        description: 'Optional. A list of comma separated language names visible on buttons or links in the interview that change the language of the interview. Overrides the EXTRA_LANGUAGES GitHub secret.'
        default: ''
      tags:
        description: 'Optional. Use a "tag expression" specify which tagged tests to run. See https://cucumber.io/docs/cucumber/api/#tag-expressions for syntax.'
        default: ''

jobs:

  interview-testing:
    runs-on: ubuntu-latest
    name: Run interview tests
    steps:
      - uses: actions/checkout@v2
      - name: Use ALKiln to run tests
        uses: suffolkLITLab/ALKiln@releases/v4
        with:
          SERVER_URL: "${{ secrets.SERVER_URL }}"
          PLAYGROUND_EMAIL: "${{ secrets.PLAYGROUND_EMAIL }}"
          PLAYGROUND_PASSWORD: "${{ secrets.PLAYGROUND_PASSWORD }}"
          PLAYGROUND_ID: "${{ secrets.PLAYGROUND_ID }}"
          EXTRA_LANGUAGES: "${{ secrets.EXTRA_LANGUAGES }}"
      - run: echo "Finished running ALKiln tests"
```

Note: we don't have a `releases/v4` branch, that's jus the format they'd use once we start doing that. We still need to decide what we're doing with action releases/tags/whatever.
