### ISSUE TITLE
Allow dev to make new issue on test failure. Our responsibility or their own customization? Docs?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#469]
[React with 😄 for option 1, react with 🎉 for option 2]

Two ways to go about this:

1. We handle it and they give inputs to our action that enable/disable it. Should the default be `true` or `false`?

Pros: We can create some kind of default and people might not need to mess with it.
Cons: Either they have to hand in a bunch more inputs or not really have any control over the issue that gets created. If our default is `true`, they will have to hand it at least one more input regardless. It seems annoying to override. See notes below about extra inputs.

2. We could just let them add the below code to their own workflow. Then they can control the contents of the issue themselves. We'd just document instructions.

Pros: They have more control and don't need to hand in extra inputs in their workflow.
Cons: They have to edit their workflow.yml more extensively, though we would provide them with the code and tell them to plop it at the end of their workflow, which is pretty easy.

The code [for creating an issue with a link to the action itself]:
```yml
      - name: If tests failed create an issue
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ALKiln tests failed
          body: |
            An ALKiln test failed. See the action at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          labels: |
            bug
```

`secrets.github_token` is something github creates automatically, so they don't have to add another secret. If we were handling it, though, they would have to give us that secret as an input for this to work if they want issues made. We might be able to add something to the `if`, but I haven't tried it. Something like:

```yml
        if: ${{ failure() && inputs.github_token && inputs.make_issue_on_failure }}
```

If they wanted to customize the issue, they'd also need to be able to hand in `title`, `body`, and `labels`.
