### ISSUE TITLE
Add: Use same variable value multiple times on one page

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#793]
Note for framework: there should be no error, just a message and a few lines in the report to warn developers.

eg:
``` yml
fields:
  - no label: repeate_var_val
    datatype: checkbox
    choices:
    - First appearance: repeated_val
    - Second appearance: repeated_val
```

Also, where one variable is set in multiple places on the page, but only one of those will appear. Something like:
```yml
fields:
  - Show field 1 or 2: show_field_1_or_2
    datatype: radio
    choices:
      - One: one
      - Two: two
  - Field 1 repeated var: repeated_variable
    show if:
      variable: show_field_1_or_2
      is: one
  - Field 2 repeated var: repeated_variable
      variable: show_field_1_or_2
      is: two
```

Another example is with the pattern of code needed to get 'other' to work sometimes:
```yml
fields:
  - no label: repeated_var_for_other
    choices:
      - Apples: apples
      - Peaches: peaches
      - Pears: pears
      - Other: custom
  - Other: fruit
    show if: 
      variable: fruit
      is: custom
```

Another would be plain old dumb variable appearing twice:
```yml
fields:
  - First appearance of var: repeate_var
    datatype: yesno
  - Second appearance of var: repeate_var
    datatype: yesno
```
