### ISSUE TITLE
Add field: Checkboxes/other things created with code with complex objects?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#797]
Something like the below? Needs AssemblyLine package. Creates double encoding.
```yml
---
sets:
  - trial_court
id: choose a court from list
question: |
  What court is your case in?
subquestion: |
  Look at your Abuse Prevention Order. 
  
  Underneath **your** name, see the court name. 
  
  Select that court from the list below:
fields:
  #- no label: trial_court
  #  datatype: object
  #  object labeler: |
  #    lambda y: y.short_label()
  #  choices: all_courts.filter_courts(allowed_courts)
  - no label: trial_court
    datatype: checkboxes
    code: |
      court_choices.filter_courts(allowed_courts)
---
code: |
  for court in all_courts:
    court.label = court.short_label()
  court_choices = all_courts
---
```
